# Название вашего воркфлоу
name: Purge jsDelivr Cache

on:
  push:
    branches: [ main ]
    paths:
      - 'script.js'
      - 'style.css'

jobs:
  purge_cache:
    runs-on: ubuntu-latest
    steps:
      - name: Purge jsDelivr cache
        # --- ИСПРАВЛЕННАЯ СТРОКА ---
        uses: steebchen/jsdelivr-purge@v1
        with:
          # Файлы для очистки
          files: '/script.js, /style.css'
